/**
 * Land a generated news YAML on main and trigger the publish pipeline.
 *
 * Flow (runs inside GitHub Actions with GH_TOKEN):
 *   branch -> commit -> push -> PR -> squash-merge -> dispatch build-news.yml
 *
 * Two non-obvious choices:
 * - We go through a PR (not a direct push to main) so every auto-published item
 *   has an auditable trail and CI validation, per repo workflow rules.
 * - We explicitly dispatch build-news.yml afterwards because pushes made with
 *   GITHUB_TOKEN do not fire other workflows' push triggers. The dispatch passes
 *   test_post_file so the social step targets exactly our file instead of
 *   relying on a HEAD~1 diff.
 */

const { execFileSync } = require('child_process');

function sh(cmd, args, opts = {}) {
  return execFileSync(cmd, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], ...opts }).trim();
}

async function publishNews({ filepath, filename, title, sourceUrl, factcheck }) {
  const branch = `content-agent/news-${filename.replace(/\.yaml$/, '')}`;

  sh('git', ['config', 'user.name', 'creditodds-content-agent']);
  sh('git', ['config', 'user.email', 'bot@creditodds.com']);
  sh('git', ['checkout', '-B', branch]);
  sh('git', ['add', filepath]);
  sh('git', ['commit', '-m', `news(content-agent): ${title}`]);
  sh('git', ['push', '-u', 'origin', branch, '--force']);

  const srcLines = (factcheck.sources || [])
    .map((s) => `- ${s.primary ? '**(primary)** ' : ''}[${s.title}](${s.url})`)
    .join('\n');
  const body = [
    `Auto-generated by the content agent from a fact-checked competitor signal.`,
    ``,
    `**Fact-check:** ${factcheck.verdict} · confidence ${factcheck.confidence}`,
    `**Notes:** ${factcheck.notes}`,
    `**Primary source:** ${sourceUrl}`,
    ``,
    `Sources:`,
    srcLines,
  ].join('\n');

  const prUrl = sh('gh', ['pr', 'create', '--title', `news(content-agent): ${title}`, '--body', body, '--head', branch]);
  sh('gh', ['pr', 'merge', branch, '--squash', '--delete-branch']);

  // Merge done — dispatch the publish pipeline against our exact file.
  sh('git', ['checkout', 'main']);
  sh('gh', ['workflow', 'run', 'build-news.yml', '--ref', 'main', '-f', `test_post_file=${filepath}`]);

  return { prUrl, branch };
}

module.exports = { publishNews };
