ALTER TABLE cards
  ADD COLUMN signup_bonus_value INT DEFAULT NULL,
  ADD COLUMN signup_bonus_type VARCHAR(10) DEFAULT NULL,
  ADD COLUMN reward_top_rate DECIMAL(5,2) DEFAULT NULL,
  ADD COLUMN reward_top_unit VARCHAR(20) DEFAULT NULL,
  ADD COLUMN apr_min DECIMAL(5,2) DEFAULT NULL,
  ADD COLUMN apr_max DECIMAL(5,2) DEFAULT NULL;
