CREATE TABLE IF NOT EXISTS user_settings (
  user_id VARCHAR(255) NOT NULL PRIMARY KEY,
  plaid_beta_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
