CREATE TABLE IF NOT EXISTS plaid_transactions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  plaid_account_row_id INT NOT NULL,
  plaid_transaction_id VARCHAR(80) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  iso_currency_code VARCHAR(8),
  unofficial_currency_code VARCHAR(8),
  date DATE NOT NULL,
  datetime TIMESTAMP NULL,
  authorized_date DATE NULL,
  authorized_datetime TIMESTAMP NULL,
  name VARCHAR(500),
  merchant_name VARCHAR(255),
  payment_channel VARCHAR(40),
  pending BOOLEAN NOT NULL DEFAULT FALSE,
  pending_transaction_id VARCHAR(80),
  account_owner VARCHAR(255),
  pfc_primary VARCHAR(80),
  pfc_detailed VARCHAR(80),
  pfc_confidence VARCHAR(20),
  transaction_code VARCHAR(40),
  raw JSON,
  removed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_plaid_txn (plaid_transaction_id),
  INDEX idx_account_date (plaid_account_row_id, date),
  INDEX idx_pending (pending),
  INDEX idx_removed (removed),
  FOREIGN KEY (plaid_account_row_id) REFERENCES user_plaid_accounts(id) ON DELETE CASCADE
);
