#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const STORES_DIR = path.join(__dirname, '..', 'data', 'stores');
const SCHEMA_FILE = path.join(STORES_DIR, 'schema.json');
const OUTPUT_FILE = path.join(__dirname, '..', 'data', 'stores.json');
// Mirror into the Lambda bundle so apps/api/src/handlers/wallet-picks-*.js
// can `require('./lib/ranker/stores.json')` without a CDN fetch. SAM only
// includes files inside the function's CodeUri, so the canonical copy in
// /data/ would otherwise be invisible to the Lambda runtime.
const LAMBDA_BUNDLE_OUTPUT = path.join(
  __dirname,
  '..',
  'apps',
  'api',
  'src',
  'lib',
  'ranker',
  'stores.json'
);
const CATEGORIES_FILE = path.join(__dirname, '..', 'data', 'categories.yaml');
const CARDS_FILE = path.join(__dirname, '..', 'data', 'cards.json');
const AFFILIATES_FILE = path.join(__dirname, '..', 'data', 'affiliates.yaml');

function loadJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function loadCategoryIds() {
  const data = yaml.load(fs.readFileSync(CATEGORIES_FILE, 'utf8'));
  return new Set(data.categories.map(c => c.id));
}

function loadCardSlugs() {
  // cards.json is generated by build-cards.js. If it hasn't been built yet,
  // skip slug cross-validation rather than blowing up — this lets a fresh
  // checkout build stores standalone, and CI runs build-cards first anyway.
  if (!fs.existsSync(CARDS_FILE)) {
    console.warn('  (warning) cards.json not found — skipping co_brand/also_earns slug validation. Run npm run build:cards first.');
    return null;
  }
  const data = loadJson(CARDS_FILE);
  return new Set((data.cards || []).map(c => c.slug));
}

// Returns a Map<slug, {url, network, cta?}>. Missing file is fine — the
// affiliate program is additive, and a fresh checkout should still build.
function loadAffiliates() {
  if (!fs.existsSync(AFFILIATES_FILE)) {
    console.warn('  (warning) affiliates.yaml not found — no affiliate links will be attached.');
    return new Map();
  }

  const data = yaml.load(fs.readFileSync(AFFILIATES_FILE, 'utf8')) || {};
  const defaultNetwork = data.network;
  const merchants = data.merchants || {};
  const errors = [];
  const result = new Map();

  for (const [slug, raw] of Object.entries(merchants)) {
    const entry = typeof raw === 'string' ? { url: raw } : raw;

    if (!entry || typeof entry.url !== 'string' || !entry.url.startsWith('https://')) {
      errors.push(`affiliates.yaml: ${slug} needs an https url`);
      continue;
    }

    const network = entry.network || defaultNetwork;
    if (!network) {
      errors.push(`affiliates.yaml: ${slug} has no network (set one on the entry or the top-level default)`);
      continue;
    }
    if (entry.cta !== undefined && typeof entry.cta !== 'string') {
      errors.push(`affiliates.yaml: ${slug} cta must be a string`);
      continue;
    }
    if (entry.offer !== undefined && typeof entry.offer !== 'string') {
      errors.push(`affiliates.yaml: ${slug} offer must be a string`);
      continue;
    }
    // The offer is interpolated as "See {offer} at {store}". A trailing period
    // or a sentence-shaped value means someone wrote a blurb, not a phrase.
    if (typeof entry.offer === 'string' && /[.!]$/.test(entry.offer.trim())) {
      errors.push(`affiliates.yaml: ${slug} offer must be a phrase, not a sentence (drop the trailing period): "${entry.offer}"`);
      continue;
    }

    result.set(slug, {
      url: entry.url,
      network,
      ...(entry.offer ? { offer: entry.offer } : {}),
      ...(entry.cta ? { cta: entry.cta } : {}),
    });
  }

  if (errors.length > 0) {
    console.error('\nAffiliate validation failed:');
    for (const err of errors) console.error(`  - ${err}`);
    process.exit(1);
  }

  return result;
}

function validateStore(store, schema, categoryIds, cardSlugs) {
  const errors = [];

  for (const field of schema.required) {
    if (store[field] === undefined || store[field] === null) {
      errors.push(`Missing required field: ${field}`);
    }
  }

  if (store.slug && !/^[a-z0-9-]+$/.test(store.slug)) {
    errors.push(`Invalid slug format: ${store.slug} (lowercase + hyphens only)`);
  }

  if (Array.isArray(store.categories)) {
    if (store.categories.length === 0) {
      errors.push('categories must have at least one entry');
    }
    for (const cat of store.categories) {
      if (!categoryIds.has(cat)) {
        errors.push(`Invalid category: ${cat} (not in categories.yaml)`);
      }
    }
  } else if (store.categories !== undefined) {
    errors.push('categories must be an array');
  }

  if (store.intro !== undefined) {
    if (typeof store.intro !== 'string') {
      errors.push('intro must be a string');
    } else if (store.intro.trim().length < 200) {
      errors.push(`intro is too short (${store.intro.trim().length} chars; min 200) — distinctive copy is required to avoid doorway-page SEO penalties`);
    }
  }

  if (store.co_brand_cards) {
    if (!Array.isArray(store.co_brand_cards)) {
      errors.push('co_brand_cards must be an array');
    } else if (cardSlugs) {
      for (const slug of store.co_brand_cards) {
        if (!cardSlugs.has(slug)) {
          errors.push(`co_brand_cards slug not found in cards.json: ${slug}`);
        }
      }
    }
  }

  if (store.also_earns) {
    if (!Array.isArray(store.also_earns)) {
      errors.push('also_earns must be an array');
    } else {
      for (const entry of store.also_earns) {
        if (!entry.card || !/^[a-z0-9-]+$/.test(entry.card)) {
          errors.push(`also_earns entry missing valid card slug: ${JSON.stringify(entry)}`);
        } else if (cardSlugs && !cardSlugs.has(entry.card)) {
          errors.push(`also_earns card slug not found in cards.json: ${entry.card}`);
        }
        if (typeof entry.rate !== 'number' || entry.rate < 0) {
          errors.push(`also_earns.rate must be a non-negative number for ${entry.card}`);
        }
        if (!['percent', 'points_per_dollar'].includes(entry.unit)) {
          errors.push(`also_earns.unit must be 'percent' or 'points_per_dollar' for ${entry.card}`);
        }
      }
    }
  }

  if (store.faq) {
    if (!Array.isArray(store.faq)) {
      errors.push('faq must be an array');
    } else {
      for (const entry of store.faq) {
        if (!entry.q || !entry.a) errors.push(`faq entry missing q or a: ${JSON.stringify(entry)}`);
      }
    }
  }

  return errors;
}

function buildStores() {
  console.log('Building stores.json from YAML files...\n');

  if (!fs.existsSync(STORES_DIR)) {
    console.error(`Stores directory missing: ${STORES_DIR}`);
    process.exit(1);
  }

  const schema = loadJson(SCHEMA_FILE);
  const categoryIds = loadCategoryIds();
  const cardSlugs = loadCardSlugs();
  const affiliates = loadAffiliates();
  const stores = [];
  const errors = [];
  const seenSlugs = new Set();

  const files = fs.readdirSync(STORES_DIR)
    .filter(f => (f.endsWith('.yaml') || f.endsWith('.yml')) && f !== 'schema.json');

  console.log(`Found ${files.length} store file(s)\n`);

  for (const file of files) {
    const filePath = path.join(STORES_DIR, file);
    console.log(`Processing: ${file}`);

    try {
      const store = yaml.load(fs.readFileSync(filePath, 'utf8'));

      const validationErrors = validateStore(store, schema, categoryIds, cardSlugs);

      if (store.slug) {
        if (seenSlugs.has(store.slug)) {
          validationErrors.push(`Duplicate slug: ${store.slug}`);
        } else {
          seenSlugs.add(store.slug);
        }
      }

      if (validationErrors.length > 0) {
        errors.push({ file, errors: validationErrors });
        console.log(`  ERROR: ${validationErrors.join('; ')}`);
        continue;
      }

      const affiliate = affiliates.get(store.slug);
      if (affiliate) store.affiliate = affiliate;

      stores.push(store);
      console.log(`  OK: ${store.name}${affiliate ? ' (+ affiliate)' : ''}`);
    } catch (err) {
      errors.push({ file, errors: [err.message] });
      console.log(`  ERROR: ${err.message}`);
    }
  }

  console.log('\n---');

  // An affiliate slug with no matching store silently drops a live link, so
  // treat it as a build error rather than a warning.
  const orphanAffiliates = [...affiliates.keys()].filter(slug => !seenSlugs.has(slug));
  if (orphanAffiliates.length > 0) {
    errors.push({
      file: 'affiliates.yaml',
      errors: orphanAffiliates.map(slug => `no store with slug "${slug}" (check data/stores/${slug}.yaml)`),
    });
  }

  if (errors.length > 0) {
    console.error(`\nValidation failed with ${errors.length} error(s):`);
    for (const { file, errors: fileErrors } of errors) {
      console.error(`  ${file}:`);
      for (const err of fileErrors) console.error(`    - ${err}`);
    }
    process.exit(1);
  }

  stores.sort((a, b) => a.name.localeCompare(b.name));

  const output = {
    generated_at: new Date().toISOString(),
    count: stores.length,
    stores,
  };

  const serialized = JSON.stringify(output, null, 2);
  fs.writeFileSync(OUTPUT_FILE, serialized);
  fs.writeFileSync(LAMBDA_BUNDLE_OUTPUT, serialized);
  console.log(`\nSuccessfully built ${stores.length} store(s) to ${OUTPUT_FILE}`);
  console.log(`  ${affiliates.size} affiliate link(s) attached`);
  console.log(`  + mirrored to Lambda bundle at ${LAMBDA_BUNDLE_OUTPUT}`);
}

buildStores();
