#!/usr/bin/env bash
#
# Publish step for the local card-news check. Runs AFTER
# `node scripts/check-card-news.js --phase=finish` has moved validated items
# into data/news/. Validates via build:news, then opens the review PR.
#
# The branch prefix "auto-news-" is load-bearing: reject-news.yml only records
# news:reject closures into data/news-rejected.yaml for branches with that
# prefix. Do not rename it.
#
# Usage:  scripts/check-card-news-publish.sh

set -euo pipefail

cd "$(dirname "$0")/.."

if [ -z "$(git status --porcelain data/news/)" ]; then
  echo "No news to propose."
  exit 0
fi

echo "=== Validating news data ==="
# build:news needs cards.json for related-card image lookups; refresh it so a
# stale local copy cannot fail the validation. Both JSON outputs are gitignored.
npm run build:cards >/dev/null
if ! npm run build:news; then
  echo "ERROR: news validation failed. The offending files are still in data/news/ — fix or remove them, then re-run." >&2
  git status --porcelain data/news/ >&2
  exit 1
fi

ORIGINAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
BRANCH="auto-news-$(date +%Y-%m-%d-%H%M%S)"

echo "=== Opening PR ==="
# Base on origin/main, not HEAD: locally this may run from a feature branch,
# and the PR must contain nothing but news YAML. The uncommitted data/news/
# files carry across the checkout because they are untracked.
git fetch -q origin main
git checkout -q -b "$BRANCH" origin/main
git add data/news/
git commit -q -m "Add auto-generated news items for $(date +%Y-%m-%d)"
git push -q -u origin "$BRANCH"

BODY_FILE="$(mktemp)"
cat > "$BODY_FILE" << 'PREOF'
## Proposed News Items

Generated by the local `card-news-local` routine (sources: r/churning News & Updates thread, r/CreditCards, Doctor of Credit, Google News; triage, source verification, and article writing done in-session).

### How to review
1. Check each YAML file in `data/news/` for accuracy against its `source_url`.
2. Verify the story is not a duplicate and is genuinely newsworthy.
3. Edit titles/summaries/bodies freely before merging.
4. Remove any item that should not ship.
5. To reject everything: add the `news:reject` label and close the PR — the rejected items are recorded so they will not be re-proposed.

### What merging does
Merging triggers `build-news.yml`: news.json to S3/CloudFront, Amplify rebuild, hero-image generation, social-media queue, and IndexNow ping.
PREOF

PR_URL=$(gh pr create --title "Auto News Update $(date +%Y-%m-%d)" --body-file "$BODY_FILE")
rm -f "$BODY_FILE"
echo "PR: $PR_URL"
git checkout -q "$ORIGINAL_BRANCH"
