#!/usr/bin/env bash
#
# Publish step for the local card-news check. Runs AFTER
# `node scripts/check-card-news.js --phase=finish` has moved validated items
# into data/news/. Validates via build:news, then opens the review PR.
#
# The branch prefix "auto-news-" is load-bearing: reject-news.yml only records
# news:reject closures into data/news-rejected.yaml for branches with that
# prefix. Do not rename it.
#
# This script never changes the branch of the checkout it runs in. It builds
# the commit inside a throwaway `git worktree` instead. That matters because
# the scheduled routines share one working tree with interactive sessions: an
# earlier version ran `git checkout -b <branch> origin/main` here and blew up
# with "Your local changes would be overwritten by checkout" the moment any
# unrelated tracked file was dirty and differed between HEAD and origin/main
# (2026-08-04: another session was mid-edit on data/cards/*.yaml belonging to
# an unpushed commit). A worktree cannot be blocked by unrelated dirt, and it
# cannot yank HEAD out from under a concurrent session either.
#
# Usage:  scripts/check-card-news-publish.sh
#         DRY_RUN=1 scripts/check-card-news-publish.sh   # no push, no PR

set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"
DRY_RUN="${DRY_RUN:-}"

if [ -z "$(git status --porcelain -- data/news/)" ]; then
  echo "No news to propose."
  exit 0
fi

echo "=== Validating news data ==="
# build:news needs cards.json for related-card image lookups; refresh it so a
# stale local copy cannot fail the validation. Both JSON outputs are gitignored.
npm run build:cards >/dev/null
if ! npm run build:news; then
  echo "ERROR: news validation failed. The offending files are still in data/news/ — fix or remove them, then re-run." >&2
  git status --porcelain -- data/news/ >&2
  exit 1
fi

# Collect exactly the news files to publish, as explicit paths. Never
# `git add data/news/` — in a shared checkout that can sweep up a file this run
# did not write. --phase=finish only ever creates new (untracked) files, so
# anything else under data/news/ is an anomaly worth stopping on.
NEWS_FILES=()
OTHER_CHANGES=()
while IFS= read -r -d '' entry; do
  status="${entry:0:2}"
  path="${entry:3}"
  if [ "$status" = "??" ]; then
    NEWS_FILES+=("$path")
  else
    OTHER_CHANGES+=("$status $path")
  fi
done < <(git status --porcelain -z -- data/news/)

if [ "${#OTHER_CHANGES[@]}" -ne 0 ]; then
  echo "ERROR: data/news/ has changes to tracked files, which this script does not publish:" >&2
  printf '  %s\n' "${OTHER_CHANGES[@]}" >&2
  echo "Resolve them by hand (commit or restore), then re-run." >&2
  exit 1
fi

if [ "${#NEWS_FILES[@]}" -eq 0 ]; then
  echo "No news to propose."
  exit 0
fi

BRANCH="auto-news-$(date +%Y-%m-%d-%H%M%S)"
WORKTREE="$(mktemp -d "${TMPDIR:-/tmp}/auto-news-wt.XXXXXX")"

cleanup() {
  cd "$REPO_ROOT"
  git worktree remove --force "$WORKTREE" 2>/dev/null || rm -rf "$WORKTREE"
  git worktree prune 2>/dev/null || true
  # The branch ref outlives the worktree, and on a dry run nothing was pushed,
  # so drop it. Must happen after the worktree is gone: git refuses to delete a
  # branch that is still checked out somewhere.
  if [ -n "$DRY_RUN" ]; then
    git branch -q -D "$BRANCH" 2>/dev/null || true
  fi
}
trap cleanup EXIT

echo "=== Opening PR ==="
# Base the branch on origin/main, not HEAD: this may run from a feature branch,
# and the PR must contain nothing but news YAML.
git fetch -q origin main
# `worktree add` creates the branch without touching this checkout's HEAD.
git worktree add -q -b "$BRANCH" "$WORKTREE" origin/main

for path in "${NEWS_FILES[@]}"; do
  mkdir -p "$WORKTREE/$(dirname "$path")"
  cp "$path" "$WORKTREE/$path"
done

cd "$WORKTREE"
git add -- "${NEWS_FILES[@]}"
git commit -q -m "Add auto-generated news items for $(date +%Y-%m-%d)"
LOCAL_SHA="$(git rev-parse HEAD)"

if [ -n "$DRY_RUN" ]; then
  echo "DRY_RUN: would push $BRANCH ($LOCAL_SHA) and open a PR with:"
  git show --stat --oneline HEAD
  exit 0
fi

git push -q -u origin "$BRANCH"

# Confirm the remote ref actually points at this commit. A push can report
# success while the branch ref lags (see the shared-checkout notes above), and
# the only later symptom is `gh pr create` failing with "No commits between".
REMOTE_SHA="$(git ls-remote origin "refs/heads/$BRANCH" | cut -f1)"
if [ "$REMOTE_SHA" != "$LOCAL_SHA" ]; then
  echo "ERROR: pushed $BRANCH but remote is at '$REMOTE_SHA', expected '$LOCAL_SHA'." >&2
  echo "Fix with: git push origin $LOCAL_SHA:refs/heads/$BRANCH" >&2
  exit 1
fi

BODY_FILE="$(mktemp)"
cat > "$BODY_FILE" << 'PREOF'
## Proposed News Items

Generated by the local `card-news-local` routine (sources: r/churning News & Updates thread, r/CreditCards, Doctor of Credit, Google News; triage, source verification, and article writing done in-session).

### How to review
1. Check each YAML file in `data/news/` for accuracy against its `source_url`.
2. Verify the story is not a duplicate and is genuinely newsworthy.
3. Edit titles/summaries/bodies freely before merging.
4. Remove any item that should not ship.
5. To reject everything: add the `news:reject` label and close the PR — the rejected items are recorded so they will not be re-proposed.

### What merging does
Merging triggers `build-news.yml`: news.json to S3/CloudFront, Amplify rebuild, hero-image generation, social-media queue, and IndexNow ping.
PREOF

PR_URL=$(gh pr create --base main --title "Auto News Update $(date +%Y-%m-%d)" --body-file "$BODY_FILE")
rm -f "$BODY_FILE"
echo "PR: $PR_URL"

# The items now live on the pushed branch, so drop the working copies to leave
# data/news/ clean for the next run's precondition check.
cd "$REPO_ROOT"
for path in "${NEWS_FILES[@]}"; do
  rm -f "$path"
done
